name: CI

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Brakeman
      run: bundle exec brakeman

    - name: Run RuboCop
      continue-on-error: true
      run: bundle exec rubocop

    - name: Run RSpec tests
      env:
        RAILS_ENV: test
      run: |
        cp config/database.yml.ci config/database.yml
        bin/rails db:create db:schema:load
        bundle exec rspec